--
-- PostgreSQL database dump
--

\restrict Fa7tHed36GNJgS0e5UiV2VH0tq9ScgXLoO8Dd7bN9uXM5YhOlP2nS2ZceVFeb6y

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: about_awards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_awards (
    award_id bigint NOT NULL,
    awarded_date date NOT NULL,
    description text,
    display_order integer NOT NULL,
    issuer character varying(200) NOT NULL,
    title character varying(200) NOT NULL,
    about_id bigint NOT NULL
);


--
-- Name: about_awards_award_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_awards ALTER COLUMN award_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_awards_award_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about_competencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_competencies (
    competency_id bigint NOT NULL,
    description character varying(1000) NOT NULL,
    display_order integer NOT NULL,
    title character varying(150) NOT NULL,
    about_id bigint NOT NULL
);


--
-- Name: about_competencies_competency_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_competencies ALTER COLUMN competency_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_competencies_competency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about_educations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_educations (
    education_id bigint NOT NULL,
    course_name character varying(300) NOT NULL,
    description text,
    display_order integer NOT NULL,
    education_type character varying(30) NOT NULL,
    end_date date,
    institution_name character varying(200) NOT NULL,
    start_date date NOT NULL,
    status character varying(100),
    about_id bigint NOT NULL,
    CONSTRAINT about_educations_education_type_check CHECK (((education_type)::text = ANY (ARRAY[('SCHOOL'::character varying)::text, ('TRAINING'::character varying)::text])))
);


--
-- Name: about_educations_education_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_educations ALTER COLUMN education_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_educations_education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_profiles (
    about_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    cta_label character varying(100) NOT NULL,
    cta_url character varying(500) NOT NULL,
    heading character varying(200) NOT NULL,
    is_published boolean NOT NULL,
    summary character varying(1000) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    singleton_key character varying(30) NOT NULL,
    background character varying(200),
    birth_date date,
    current_focus character varying(200),
    interests character varying(500),
    location character varying(200),
    name_en character varying(100),
    name_ko character varying(100),
    "position" character varying(150),
    profile_image_url text
);


--
-- Name: about_profiles_about_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_profiles ALTER COLUMN about_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_profiles_about_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about_sections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_sections (
    section_id bigint NOT NULL,
    content_html text NOT NULL,
    display_order integer NOT NULL,
    title character varying(150) NOT NULL,
    about_id bigint NOT NULL,
    section_type character varying(30),
    CONSTRAINT about_sections_section_type_check CHECK (((section_type)::text = ANY (ARRAY[('TECHNICAL_STACK'::character varying)::text, ('TROUBLESHOOTING'::character varying)::text, ('STORY'::character varying)::text])))
);


--
-- Name: about_sections_section_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_sections ALTER COLUMN section_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_sections_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about_skill_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_skill_categories (
    skill_category_id bigint NOT NULL,
    description character varying(500),
    display_order integer NOT NULL,
    title character varying(150) NOT NULL,
    about_id bigint NOT NULL
);


--
-- Name: about_skill_categories_skill_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_skill_categories ALTER COLUMN skill_category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_skill_categories_skill_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_skills (
    skill_id bigint NOT NULL,
    description character varying(300),
    display_order integer NOT NULL,
    logo_url text,
    name character varying(100) NOT NULL,
    skill_category_id bigint NOT NULL
);


--
-- Name: about_skills_skill_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_skills ALTER COLUMN skill_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_skills_skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about_work_experiences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_work_experiences (
    experience_id bigint NOT NULL,
    company_name character varying(200) NOT NULL,
    description_html text NOT NULL,
    display_order integer NOT NULL,
    employment_type character varying(30) NOT NULL,
    end_date date,
    position_title character varying(200) NOT NULL,
    start_date date NOT NULL,
    about_id bigint NOT NULL,
    CONSTRAINT about_work_experiences_employment_type_check CHECK (((employment_type)::text = ANY (ARRAY[('FULL_TIME'::character varying)::text, ('FREELANCE'::character varying)::text, ('INTERN'::character varying)::text, ('CONTRACT'::character varying)::text])))
);


--
-- Name: about_work_experiences_experience_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_work_experiences ALTER COLUMN experience_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_work_experiences_experience_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_users (
    admin_user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    enabled boolean NOT NULL,
    password_hash character varying(100) NOT NULL,
    role character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(100) NOT NULL,
    CONSTRAINT admin_users_role_check CHECK (((role)::text = 'ADMIN'::text))
);


--
-- Name: admin_users_admin_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_users ALTER COLUMN admin_user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_users_admin_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_profiles (
    contact_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(1000) NOT NULL,
    email character varying(255) NOT NULL,
    github_url character varying(500) NOT NULL,
    heading character varying(200) NOT NULL,
    linkedin_url character varying(500),
    is_published boolean NOT NULL,
    resume_file_url character varying(1000),
    resume_label character varying(100) NOT NULL,
    resume_original_file_name character varying(500),
    singleton_key character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: contact_profiles_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_profiles ALTER COLUMN contact_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_profiles_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_images (
    project_image_id bigint NOT NULL,
    caption character varying(300),
    display_order integer NOT NULL,
    image_type character varying(50) NOT NULL,
    image_url text NOT NULL,
    project_id bigint NOT NULL,
    section_id bigint,
    CONSTRAINT project_images_image_type_check CHECK (((image_type)::text = ANY (ARRAY[('THUMBNAIL'::character varying)::text, ('MAIN'::character varying)::text, ('DETAIL'::character varying)::text, ('ERD'::character varying)::text, ('ARCHITECTURE'::character varying)::text, ('SCREENSHOT'::character varying)::text])))
);


--
-- Name: project_images_project_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_images ALTER COLUMN project_image_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_images_project_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_links (
    project_link_id bigint NOT NULL,
    display_order integer NOT NULL,
    link_name character varying(100) NOT NULL,
    link_type character varying(50) NOT NULL,
    url text NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT project_links_link_type_check CHECK (((link_type)::text = ANY (ARRAY[('GITHUB'::character varying)::text, ('DEPLOY'::character varying)::text, ('PDF'::character varying)::text, ('NOTION'::character varying)::text, ('RESUME'::character varying)::text, ('SARAMIN'::character varying)::text, ('ETC'::character varying)::text])))
);


--
-- Name: project_links_project_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_links ALTER COLUMN project_link_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_links_project_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_sections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_sections (
    section_id bigint NOT NULL,
    content text,
    display_order integer NOT NULL,
    section_type character varying(100) NOT NULL,
    title character varying(200),
    project_id bigint NOT NULL,
    CONSTRAINT project_sections_section_type_check CHECK (((section_type)::text = ANY (ARRAY[('CONTENTS'::character varying)::text, ('OVERVIEW'::character varying)::text, ('MY_ROLE'::character varying)::text, ('TECH_STACK'::character varying)::text, ('KEY_FEATURES'::character varying)::text, ('ARCHITECTURE'::character varying)::text, ('DATABASE_ERD'::character varying)::text, ('WORKFLOW'::character varying)::text, ('TROUBLESHOOTING'::character varying)::text, ('RESULT'::character varying)::text, ('LINKS'::character varying)::text])))
);


--
-- Name: project_sections_section_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_sections ALTER COLUMN section_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_sections_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_techs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_techs (
    project_tech_id bigint NOT NULL,
    display_order integer NOT NULL,
    tech_category character varying(100),
    tech_name character varying(100) NOT NULL,
    project_id bigint NOT NULL
);


--
-- Name: project_techs_project_tech_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_techs ALTER COLUMN project_tech_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_techs_project_tech_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    project_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    display_order integer NOT NULL,
    end_date date,
    project_type character varying(200) NOT NULL,
    is_published boolean NOT NULL,
    role text,
    slug character varying(200) NOT NULL,
    start_date date,
    summary text NOT NULL,
    team_name character varying(200),
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT projects_project_type_check CHECK (((project_type)::text = ANY (ARRAY[('TEAM'::character varying)::text, ('PERSONAL'::character varying)::text])))
);


--
-- Name: projects_project_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects ALTER COLUMN project_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: research_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.research_posts (
    research_id bigint NOT NULL,
    category character varying(100) NOT NULL,
    content_html text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    is_published boolean NOT NULL,
    published_at timestamp(6) without time zone,
    slug character varying(200) NOT NULL,
    summary text NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: research_posts_research_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.research_posts ALTER COLUMN research_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.research_posts_research_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about_awards about_awards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_awards
    ADD CONSTRAINT about_awards_pkey PRIMARY KEY (award_id);


--
-- Name: about_competencies about_competencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_competencies
    ADD CONSTRAINT about_competencies_pkey PRIMARY KEY (competency_id);


--
-- Name: about_educations about_educations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_educations
    ADD CONSTRAINT about_educations_pkey PRIMARY KEY (education_id);


--
-- Name: about_profiles about_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_profiles
    ADD CONSTRAINT about_profiles_pkey PRIMARY KEY (about_id);


--
-- Name: about_sections about_sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_sections
    ADD CONSTRAINT about_sections_pkey PRIMARY KEY (section_id);


--
-- Name: about_skill_categories about_skill_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_skill_categories
    ADD CONSTRAINT about_skill_categories_pkey PRIMARY KEY (skill_category_id);


--
-- Name: about_skills about_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_skills
    ADD CONSTRAINT about_skills_pkey PRIMARY KEY (skill_id);


--
-- Name: about_work_experiences about_work_experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_work_experiences
    ADD CONSTRAINT about_work_experiences_pkey PRIMARY KEY (experience_id);


--
-- Name: admin_users admin_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (admin_user_id);


--
-- Name: contact_profiles contact_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_profiles
    ADD CONSTRAINT contact_profiles_pkey PRIMARY KEY (contact_id);


--
-- Name: project_images project_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_images
    ADD CONSTRAINT project_images_pkey PRIMARY KEY (project_image_id);


--
-- Name: project_links project_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_links
    ADD CONSTRAINT project_links_pkey PRIMARY KEY (project_link_id);


--
-- Name: project_sections project_sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_sections
    ADD CONSTRAINT project_sections_pkey PRIMARY KEY (section_id);


--
-- Name: project_techs project_techs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_techs
    ADD CONSTRAINT project_techs_pkey PRIMARY KEY (project_tech_id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (project_id);


--
-- Name: research_posts research_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.research_posts
    ADD CONSTRAINT research_posts_pkey PRIMARY KEY (research_id);


--
-- Name: research_posts uk3es3fk90tkycdwh08he9m05dj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.research_posts
    ADD CONSTRAINT uk3es3fk90tkycdwh08he9m05dj UNIQUE (title);


--
-- Name: about_profiles uk_about_profiles_singleton_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_profiles
    ADD CONSTRAINT uk_about_profiles_singleton_key UNIQUE (singleton_key);


--
-- Name: admin_users uk_admin_users_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT uk_admin_users_username UNIQUE (username);


--
-- Name: contact_profiles uk_contact_profiles_singleton_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_profiles
    ADD CONSTRAINT uk_contact_profiles_singleton_key UNIQUE (singleton_key);


--
-- Name: projects ukcxqk67qijm09gpgig8a997mb0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT ukcxqk67qijm09gpgig8a997mb0 UNIQUE (slug);


--
-- Name: research_posts ukey2m7x5gd2ibv3pvwtbwsv5s3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.research_posts
    ADD CONSTRAINT ukey2m7x5gd2ibv3pvwtbwsv5s3 UNIQUE (slug);


--
-- Name: about_sections fk6cxw5tttbceds7w5w5it10hdb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_sections
    ADD CONSTRAINT fk6cxw5tttbceds7w5w5it10hdb FOREIGN KEY (about_id) REFERENCES public.about_profiles(about_id);


--
-- Name: about_educations fk7dxan8ab39mg6rum5taco8yx7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_educations
    ADD CONSTRAINT fk7dxan8ab39mg6rum5taco8yx7 FOREIGN KEY (about_id) REFERENCES public.about_profiles(about_id);


--
-- Name: project_techs fk8shmocsvpchflbnt1o08o5vbf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_techs
    ADD CONSTRAINT fk8shmocsvpchflbnt1o08o5vbf FOREIGN KEY (project_id) REFERENCES public.projects(project_id);


--
-- Name: about_awards fkc0q6avjptr6wrh9triitedm91; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_awards
    ADD CONSTRAINT fkc0q6avjptr6wrh9triitedm91 FOREIGN KEY (about_id) REFERENCES public.about_profiles(about_id);


--
-- Name: project_images fkcvn966ekinkgaekjufkv2uybu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_images
    ADD CONSTRAINT fkcvn966ekinkgaekjufkv2uybu FOREIGN KEY (section_id) REFERENCES public.project_sections(section_id);


--
-- Name: about_skills fkdq155ttfwnvm85bui8egxjqcj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_skills
    ADD CONSTRAINT fkdq155ttfwnvm85bui8egxjqcj FOREIGN KEY (skill_category_id) REFERENCES public.about_skill_categories(skill_category_id);


--
-- Name: about_competencies fkg2cx131788rambshuygalvngh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_competencies
    ADD CONSTRAINT fkg2cx131788rambshuygalvngh FOREIGN KEY (about_id) REFERENCES public.about_profiles(about_id);


--
-- Name: about_work_experiences fkgrabf0ddypndwvdbc8oyc8vrd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_work_experiences
    ADD CONSTRAINT fkgrabf0ddypndwvdbc8oyc8vrd FOREIGN KEY (about_id) REFERENCES public.about_profiles(about_id);


--
-- Name: project_sections fkk83n7q97gjflww97lvm5bimqd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_sections
    ADD CONSTRAINT fkk83n7q97gjflww97lvm5bimqd FOREIGN KEY (project_id) REFERENCES public.projects(project_id);


--
-- Name: project_links fkmo4lq56vrdc8rw945qp25u0dh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_links
    ADD CONSTRAINT fkmo4lq56vrdc8rw945qp25u0dh FOREIGN KEY (project_id) REFERENCES public.projects(project_id);


--
-- Name: project_images fkoej10untas4roy2rqxcmbdj42; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_images
    ADD CONSTRAINT fkoej10untas4roy2rqxcmbdj42 FOREIGN KEY (project_id) REFERENCES public.projects(project_id);


--
-- Name: about_skill_categories fkpgrhcm3t0xmfp000bjfyb00yy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_skill_categories
    ADD CONSTRAINT fkpgrhcm3t0xmfp000bjfyb00yy FOREIGN KEY (about_id) REFERENCES public.about_profiles(about_id);


--
-- PostgreSQL database dump complete
--

\unrestrict Fa7tHed36GNJgS0e5UiV2VH0tq9ScgXLoO8Dd7bN9uXM5YhOlP2nS2ZceVFeb6y
