# packageName    : main.resources
# fileName       : application.yml
# author         : Song
# date           : 2026-06-25
# description    : 포트폴리오 백엔드 기본 정보 및 JPA 설정, 로컬 환경 활성화
# ===========================================================
# DATE              AUTHOR             NOTE
# -----------------------------------------------------------
# 2026-06-25        Song               최초 생성
# 2026-07-28        Song               multipart 용량 지정
#/

server:
  port: 8081

spring:
  application:
    name: portfolio-backend

  profiles:
    active: local

  config:
    import: optional:classpath:application-local.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  upload:
    image-directory: ${IMAGE_UPLOAD_DIR:./uploads/projects}
    image-url-prefix: ${IMAGE_URL_PREFIX:/uploads/projects}
    max-image-size: 10485760

    # DB에서 참조하지 않는 오래된 이미지 파일 정리
    orphan-cleanup-enabled: ${IMAGE_ORPHAN_CLEANIP_ENABLED:true}
    orphan-retention-hours: ${IMAGE_ORPHAN_RETENTION_HOURS:24}
    #orphan-retention-hours: ${IMAGE_ORPHAN_RETENTION_HOURS:1}
    orphan-cleanup-cron: "${IMAGE_ORPHAN_CLEANUP_CRON:0 30 3 * * *}"
    #orphan-cleanup-cron: "${IMAGE_ORPHAN_CLEANUP_CRON:0/10 * * * * *}"
    orphan-cleanup-zone: ${IMAGE_ORPHAN_CLEANUP_ZONE:Asia/Seoul}

#요청 URL:
#  /uploads/projects/2026/07/uuid.png
#
#실제 파일:
#  /프로젝트실행경로/uploads/projects/2026/07/uuid.png