#spring.application.name=backend
#application.properties 미사용 => application.yml 사용

#이유1) 중복 코드 제거와 계층 구조 활용으로 가독성 업
# - application.properties (기존 방식)
#server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver

# - application.yml 방식
# server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/portfolio_db
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver